### ISSUE TITLE
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');

### ISSUE THREAD

**Issue by tablecell** [ivyjs/framework#7]
```ivy  new test 
cd test 
node .
```

path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:495:7)
    at Function.requireFromFolder (node_modules\ivyframework\src\Util\Helper.js:26:21)
    at Object.<anonymous> (bootstrap\index.js:17:8)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)

node_modules\ivyframework\src\Util\Helper.js:24
```
		folderPath = path.join(process.env.PWD, folderPath);

```
windows platform  have not ENV variable   PWD

**Comment by SnigdhaAgarwal6** [comment]
Hi, I am also facing the same issue, can someone suggest what shall be done.
